using System;
using System.Collections.Generic;
using aspnetapp.Collections;

namespace aspnetapp.Controllers
{
    public partial class FilterBuilder
    {
        private static void FillGenerated()
        {
            var account = new Account();
            var query = new FilterQuery();
            query.fnamesIndexes = new HList<ushort> {1};
            foreach (var combination in combinations())
            {
                //TODO: Sort predicate by heavyness
                Predicate predicate = CreateDelegate(combination);
                predicate(account, query); //Force method compilations
                Cache.Add(combination, predicate);
            }
        }

        private static FilterTypes[] combinations() => new FilterTypes[]
        {
            FilterTypes.sex_eq | FilterTypes.country_eq,
            FilterTypes.interests_any | FilterTypes.joined,
            FilterTypes.city_any | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.joined,
            FilterTypes.status_eq | FilterTypes.joined,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.birth_lt,
            FilterTypes.city_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.city_eq | FilterTypes.interests_all,
            FilterTypes.joined | FilterTypes.likes_one,
            FilterTypes.status_eq | FilterTypes.city_not_null,
            FilterTypes.phone_not_null | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.interests_all,
            FilterTypes.birth_gt | FilterTypes.likes_all | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.birth_lt | FilterTypes.premium_now,
            FilterTypes.birth_gt | FilterTypes.likes_all | FilterTypes.premium_not_null,
            FilterTypes.status_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.interests_any,
            FilterTypes.status_neq | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.country_not_null,
            FilterTypes.status_neq | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.country_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_eq,
            FilterTypes.status_neq | FilterTypes.interests_any,
            FilterTypes.birth_year | FilterTypes.likes_one,
            FilterTypes.phone_not_null | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.country_null,
            FilterTypes.birth_lt | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.interests_all,
            FilterTypes.city_eq | FilterTypes.joined,
            FilterTypes.sex_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.country_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.city_eq,
            FilterTypes.status_eq | FilterTypes.birth_gt,
            FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.interests_all,
            FilterTypes.country_eq | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.interests_any,
            FilterTypes.status_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.city_any,
            FilterTypes.email_domain | FilterTypes.country_null,
            FilterTypes.likes_all | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.interests_all | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.email_gt,
            FilterTypes.email_domain | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.interests_any | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.city_not_null,
            FilterTypes.sname_not_null | FilterTypes.country_not_null,
            FilterTypes.country_eq | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.likes_all,
            FilterTypes.country_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.birth_lt,
            FilterTypes.interests_all | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.city_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.birth_gt,
            FilterTypes.country_eq | FilterTypes.joined,
            FilterTypes.status_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.country_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.city_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.country_eq,
            FilterTypes.email_domain | FilterTypes.city_not_null,
            FilterTypes.status_eq | FilterTypes.birth_gt | FilterTypes.likes_all,
            FilterTypes.country_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.country_not_null,
            FilterTypes.phone_not_null | FilterTypes.country_null,
            FilterTypes.status_neq | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.email_domain,
            FilterTypes.birth_year | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.city_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.city_null,
            FilterTypes.email_lt | FilterTypes.country_null,
            FilterTypes.city_eq | FilterTypes.birth_gt,
            FilterTypes.interests_all | FilterTypes.likes_all | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.fname_any,
            FilterTypes.interests_any | FilterTypes.likes_all | FilterTypes.premium_now,
            FilterTypes.status_neq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.city_not_null,
            FilterTypes.email_domain | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.country_null,
            FilterTypes.interests_any | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.phone_code,
            FilterTypes.birth_gt | FilterTypes.premium_now,
            FilterTypes.status_neq | FilterTypes.interests_all | FilterTypes.likes_all,
            FilterTypes.status_neq | FilterTypes.birth_lt | FilterTypes.likes_all,
            FilterTypes.status_neq | FilterTypes.birth_gt,
            FilterTypes.fname_any | FilterTypes.country_null,
            FilterTypes.status_neq | FilterTypes.birth_year | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.country_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.country_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.interests_any | FilterTypes.premium_now,
            FilterTypes.birth_lt | FilterTypes.likes_all | FilterTypes.premium_null,
            FilterTypes.status_neq | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.email_lt,
            FilterTypes.birth_year | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.interests_any,
            FilterTypes.email_lt | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.country_eq,
            FilterTypes.country_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.city_eq,
            FilterTypes.interests_any | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.birth_lt,
            FilterTypes.interests_any | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.interests_all,
            FilterTypes.likes_all | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.birth_year,
            FilterTypes.status_eq | FilterTypes.interests_any | FilterTypes.likes_all,
            FilterTypes.email_domain | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.country_not_null | FilterTypes.interests_any,
            FilterTypes.interests_all | FilterTypes.premium_now,
            FilterTypes.status_neq | FilterTypes.birth_gt | FilterTypes.likes_all,
            FilterTypes.interests_all | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.birth_year,
            FilterTypes.email_lt | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.country_not_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.interests_any | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.city_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.birth_gt | FilterTypes.premium_null,
            FilterTypes.email_lt | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_null,
            FilterTypes.status_eq | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.birth_gt,
            FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.city_any | FilterTypes.birth_gt,
            FilterTypes.country_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.city_any | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.country_eq,
            FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.country_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.country_eq | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.birth_lt,
            FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.interests_all,
            FilterTypes.city_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.city_any,
            FilterTypes.interests_all | FilterTypes.premium_null,
            FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.premium_null,
            FilterTypes.sname_starts | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.birth_gt,
            FilterTypes.email_domain | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.city_eq,
            FilterTypes.city_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.country_not_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.country_null,
            FilterTypes.birth_year | FilterTypes.likes_all | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.city_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.birth_year | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.phone_not_null,
            FilterTypes.sex_eq | FilterTypes.country_eq | FilterTypes.birth_gt,
            FilterTypes.likes_all | FilterTypes.premium_not_null,
            FilterTypes.email_gt | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.interests_any,
            FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.birth_year,
            FilterTypes.city_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.birth_year | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.country_null,
            FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.interests_all,
            FilterTypes.city_any | FilterTypes.interests_any,
            FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.birth_gt,
            FilterTypes.sname_starts | FilterTypes.country_eq,
            FilterTypes.country_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.birth_gt,
            FilterTypes.interests_any | FilterTypes.premium_now,
            FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.country_not_null,
            FilterTypes.interests_all | FilterTypes.likes_all | FilterTypes.premium_now,
            FilterTypes.birth_year | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.city_any,
            FilterTypes.status_eq | FilterTypes.birth_year | FilterTypes.likes_all,
            FilterTypes.status_eq | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.interests_all | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.city_any | FilterTypes.birth_year,
            FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.interests_any,
            FilterTypes.city_null | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.birth_gt,
            FilterTypes.country_eq | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.interests_all,
            FilterTypes.email_gt | FilterTypes.country_not_null,
            FilterTypes.status_neq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.phone_null,
            FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.birth_gt | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.fname_not_null,
            FilterTypes.sex_eq | FilterTypes.country_null | FilterTypes.birth_lt,
            FilterTypes.city_not_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_not_null,
            FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.interests_any,
            FilterTypes.status_eq | FilterTypes.country_eq,
            FilterTypes.birth_gt | FilterTypes.likes_all,
            FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.interests_all,
            FilterTypes.status_neq | FilterTypes.interests_any | FilterTypes.likes_all,
            FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.city_eq | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.birth_gt,
            FilterTypes.phone_code | FilterTypes.city_not_null,
            FilterTypes.sname_starts | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.city_any,
            FilterTypes.fname_not_null | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.sname_starts,
            FilterTypes.sex_eq | FilterTypes.birth_gt | FilterTypes.premium_not_null,
            FilterTypes.birth_lt | FilterTypes.likes_all | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.city_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.sname_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.country_null | FilterTypes.birth_year,
            FilterTypes.fname_not_null | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.city_eq,
            FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.interests_all,
            FilterTypes.city_eq | FilterTypes.birth_lt,
            FilterTypes.email_gt | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.city_not_null | FilterTypes.interests_any,
            FilterTypes.email_lt | FilterTypes.country_eq,
            FilterTypes.phone_code | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.birth_gt,
            FilterTypes.country_null | FilterTypes.birth_lt,
            FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.interests_any,
            FilterTypes.email_gt | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.birth_gt,
            FilterTypes.birth_gt | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.city_eq | FilterTypes.birth_gt,
            FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.country_null | FilterTypes.birth_gt,
            FilterTypes.birth_lt | FilterTypes.premium_now,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.city_not_null | FilterTypes.interests_all,
            FilterTypes.status_neq | FilterTypes.city_eq,
            FilterTypes.sname_not_null | FilterTypes.country_eq,
            FilterTypes.status_eq | FilterTypes.birth_lt | FilterTypes.likes_all,
            FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_gt | FilterTypes.country_not_null,
            FilterTypes.fname_not_null | FilterTypes.city_eq,
            FilterTypes.interests_any | FilterTypes.likes_all | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.birth_year,
            FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.city_null,
            FilterTypes.phone_code | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.country_null,
            FilterTypes.status_eq | FilterTypes.interests_all | FilterTypes.likes_all,
            FilterTypes.sex_eq | FilterTypes.interests_all | FilterTypes.premium_not_null,
            FilterTypes.country_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.city_any | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.birth_year,
            FilterTypes.sname_starts | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.country_not_null,
            FilterTypes.fname_any | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.birth_year,
            FilterTypes.fname_any | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.interests_any,
            FilterTypes.status_neq | FilterTypes.country_not_null,
            FilterTypes.fname_any | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.country_null,
            FilterTypes.city_any | FilterTypes.birth_gt,
            FilterTypes.status_neq | FilterTypes.country_null,
            FilterTypes.phone_code | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.country_not_null | FilterTypes.birth_lt,
            FilterTypes.sname_not_null | FilterTypes.country_null,
            FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.country_eq,
            FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.interests_any,
            FilterTypes.country_not_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.interests_any,
            FilterTypes.birth_lt | FilterTypes.likes_all | FilterTypes.premium_not_null,
            FilterTypes.phone_null | FilterTypes.country_not_null,
            FilterTypes.city_any | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.birth_lt,
            FilterTypes.interests_any | FilterTypes.likes_all | FilterTypes.premium_null,
            FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.birth_lt,
            FilterTypes.birth_gt | FilterTypes.premium_null,
            FilterTypes.sname_not_null | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.birth_lt | FilterTypes.premium_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.city_any | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.city_any,
            FilterTypes.city_any | FilterTypes.birth_year,
            FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.birth_year,
            FilterTypes.birth_lt | FilterTypes.premium_not_null,
            FilterTypes.email_gt | FilterTypes.city_eq,
            FilterTypes.interests_all | FilterTypes.likes_all | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.fname_any | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.country_eq,
            FilterTypes.country_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.birth_lt,
            FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.city_null | FilterTypes.birth_gt,
            FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.interests_any,
            FilterTypes.status_eq | FilterTypes.country_not_null,
            FilterTypes.sname_not_null | FilterTypes.city_null,
            FilterTypes.status_eq | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.country_eq,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.city_any,
            FilterTypes.phone_code | FilterTypes.country_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.interests_all,
            FilterTypes.email_lt | FilterTypes.country_not_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.birth_lt,
            FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.birth_gt,
            FilterTypes.phone_null | FilterTypes.country_eq,
            FilterTypes.fname_not_null | FilterTypes.country_eq,
            FilterTypes.birth_year | FilterTypes.likes_all | FilterTypes.premium_not_null,
            FilterTypes.fname_any | FilterTypes.city_not_null,
            FilterTypes.city_eq | FilterTypes.interests_any,
            FilterTypes.status_eq | FilterTypes.city_any,
            FilterTypes.email_lt | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.sname_not_null | FilterTypes.city_not_null,
            FilterTypes.email_domain | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_not_null,
            FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.email_domain | FilterTypes.city_not_null,
            FilterTypes.birth_year | FilterTypes.likes_all | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.birth_year,
            FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.interests_all,
            FilterTypes.country_null | FilterTypes.interests_all,
            FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.email_lt | FilterTypes.city_null,
            FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.interests_any,
            FilterTypes.birth_year | FilterTypes.premium_not_null,
            FilterTypes.city_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.sname_starts | FilterTypes.city_null,
            FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.birth_lt,
            FilterTypes.country_not_null | FilterTypes.birth_lt,
            FilterTypes.birth_lt | FilterTypes.premium_null,
            FilterTypes.status_eq | FilterTypes.city_null,
            FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.interests_all,
            FilterTypes.email_gt | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.city_any,
            FilterTypes.sname_not_null | FilterTypes.city_any,
            FilterTypes.sname_not_null | FilterTypes.city_not_null,
            FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.birth_gt,
            FilterTypes.country_not_null | FilterTypes.birth_year,
            FilterTypes.sname_starts | FilterTypes.city_any,
            FilterTypes.fname_not_null | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.city_not_null | FilterTypes.birth_year,
            FilterTypes.status_neq | FilterTypes.city_any | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.interests_all,
            FilterTypes.phone_not_null | FilterTypes.city_null,
            FilterTypes.birth_gt | FilterTypes.likes_all | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.interests_all,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.city_null,
            FilterTypes.city_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.birth_gt,
            FilterTypes.city_null | FilterTypes.birth_gt,
            FilterTypes.status_neq | FilterTypes.country_eq | FilterTypes.birth_gt,
            FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.birth_lt,
            FilterTypes.fname_any | FilterTypes.city_any,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.city_not_null,
            FilterTypes.sname_starts | FilterTypes.city_null,
            FilterTypes.phone_code | FilterTypes.city_eq,
            FilterTypes.sex_eq | FilterTypes.birth_lt | FilterTypes.premium_null,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.interests_any,
            FilterTypes.fname_not_null | FilterTypes.city_null,
            FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.interests_all,
            FilterTypes.status_eq | FilterTypes.country_null | FilterTypes.birth_lt,
            FilterTypes.phone_null | FilterTypes.country_null,
            FilterTypes.city_not_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.city_not_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.city_null | FilterTypes.birth_year,
            FilterTypes.sname_starts | FilterTypes.city_not_null,
            FilterTypes.phone_not_null | FilterTypes.city_eq,
            FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.birth_year,
            FilterTypes.fname_any | FilterTypes.city_eq,
            FilterTypes.phone_null | FilterTypes.city_not_null,
            FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.phone_code | FilterTypes.city_not_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.country_not_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.birth_lt,
            FilterTypes.email_gt | FilterTypes.city_null,
            FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.birth_year,
            FilterTypes.sex_eq | FilterTypes.birth_year | FilterTypes.premium_not_null,
            FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.birth_year,
            FilterTypes.status_eq | FilterTypes.country_eq | FilterTypes.birth_gt,
            FilterTypes.phone_not_null | FilterTypes.city_not_null,
            FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.interests_any,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.city_not_null,
            FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.phone_null | FilterTypes.city_eq,
            FilterTypes.phone_null | FilterTypes.city_null,
            FilterTypes.sex_eq | FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.interests_all,
            FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.birth_lt,
            FilterTypes.status_eq | FilterTypes.city_eq | FilterTypes.interests_any,
            FilterTypes.fname_not_null | FilterTypes.city_not_null,
            FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.birth_gt,
            FilterTypes.birth_year | FilterTypes.premium_null,
            FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.birth_gt,
            FilterTypes.status_eq | FilterTypes.city_null | FilterTypes.interests_any,
            FilterTypes.city_not_null | FilterTypes.birth_year,
            FilterTypes.status_eq | FilterTypes.city_any | FilterTypes.birth_lt,
            FilterTypes.sex_eq | FilterTypes.fname_not_null | FilterTypes.city_null,
            FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.birth_gt,
            FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.birth_year,
            FilterTypes.status_eq | FilterTypes.city_not_null | FilterTypes.birth_gt,
            FilterTypes.phone_code | FilterTypes.city_null,
            FilterTypes.phone_null | FilterTypes.city_any,
            FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.birth_lt,
            FilterTypes.city_not_null | FilterTypes.birth_gt,
            FilterTypes.sex_eq | FilterTypes.phone_not_null | FilterTypes.city_null,
            FilterTypes.phone_not_null | FilterTypes.country_not_null,
            FilterTypes.phone_null | FilterTypes.city_eq,
            FilterTypes.status_neq | FilterTypes.country_null | FilterTypes.birth_year,
            FilterTypes.status_neq | FilterTypes.country_not_null | FilterTypes.birth_year,
            FilterTypes.status_neq | FilterTypes.city_null | FilterTypes.birth_gt,
            FilterTypes.status_neq | FilterTypes.city_eq | FilterTypes.birth_lt,
            FilterTypes.status_neq | FilterTypes.city_not_null | FilterTypes.birth_lt,
        };
    }
}